apiVersion: v1
kind: Service
metadata:
  name: airflow-mysql
  namespace: airflow
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: airflow-mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-mysql
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-mysql
  template:
    metadata:
      labels:
        app: airflow-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: airflow
            - name: MYSQL_USER
              value: airflow
            - name: MYSQL_PASSWORD
              value: airflow_pass
          ports:
            - containerPort: 3306
